---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# coreRlessons

<!-- badges: start -->
<!-- badges: end -->

This package contains all lesson-specific material (Quarto documents, images, etc) to build courses using the coreR package.

## Installation

You can install the development version of coreRlessons from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("nceas-learning-hub/coreRlessons")
```

# From NCEAS/nceas-training (update!):

This repository contains lessons used in NCEAS training events. The lessons are all written in RMarkdown and set up so that they build as a bookdown. 

To contribute, see [our contributing document](contributing.md)

## Customizing Materials

To create a custom book for a specific training, create a new branch for the training event (eg 2019-11-RRCourse). In that branch, you can make changes to _bookdown.yml to specify which content to include, and you can modify chapters. The built book should be hosted on another repository specific to that training event, **not** this repository. Please do not commit built versions of the book. Additionally, when adding material please carefully consider file size. PDF presentations should be compressed, and data files, if absolutely necessary, should be small (< 1MB). 

## Updating Materials

Changes to chapters that would be beneficial to other training events should be merged back into the master branch.

